"""MANIFEST money-scope — sinh 2026-07-31 từ discovery, PIN CỨNG (D-M3-08 cơ chế 2).

Cập nhật manifest = diff review được. Scope mới chạm token tiền mà không có ở đây
⇒ test_money_manifest_is_complete ĐỎ (chặn đường lách "viết hàm mới"). Scope bị
xoá/đổi tên ⇒ test_money_manifest_has_no_dead_entries ĐỎ (chống manifest mục).

Lớp: MONEY (mặc định nghiêm — token fatigue trong đây là vi phạm) · NOT_MONEY ·
VETO (lan can được đọc mệt) · WORLD_PHYSIOLOGY (Phase B/E11 — HÔM NAY RỖNG:
world sẽ khai cơ chế mệt→hiệu-suất vào đây CÓ KIỂM SOÁT; advisor đọc F vẫn đỏ).
"""

MANIFEST: dict[tuple[str, str], str] = {
    ('src/gsm_core/advisor/context_pack.py', 'build_context_pack'): "MONEY",
    # Guardrail text-only: rejects income promises/fabricated digits but never computes payout.
    ('src/gsm_core/advisor/checkpoint_presenter.py', 'verify_agent_output'): "NOT_MONEY",
    ('src/gsm_core/advisor/templates.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/advisor/templates.py', '_khoan_sentence'): "MONEY",
    ('src/gsm_core/advisor/templates.py', '_mission_sentence'): "MONEY",
    ('src/gsm_core/advisor/templates.py', '_penalty_sentence'): "MONEY",
    ('src/gsm_core/advisor/templates.py', 'render_template'): "MONEY",
    ('src/gsm_core/features/bonus_gap.py', 'derive_bonus_gap_input'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', '_income_row'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', 'derive_bonus_gap_input_l1r'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', 'derive_mission_select_input_l1r'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', 'derive_penalty_explain_input_l1r'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', 'derive_session_summary_input_l1r'): "MONEY",
    ('src/gsm_core/features/from_l1r.py', 'derive_weekly_khoan_input_l1r'): "MONEY",
    ('src/gsm_core/features/session_summary.py', 'derive_session_summary_input'): "MONEY",
    ('src/gsm_core/mockgen/adapter_sim.py', '_tables_from_run'): "MONEY",
    ('src/gsm_core/mockgen/generate.py', 'verify_round1'): "MONEY",
    ('src/gsm_core/mockgen/generate.py', 'verify_round3'): "MONEY",
    ('src/gsm_core/mockgen/gsm_spec.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/mockgen/profiles.py', '_profile'): "MONEY",
    ('src/gsm_core/mockgen/realdata.py', '_emit_day'): "MONEY",
    ('src/gsm_core/mockgen/realdata.py', 'build_weekly_and_missions'): "MONEY",
    ('src/gsm_core/mockgen/realdata.py', 'rule_based_trips'): "MONEY",
    ('src/gsm_core/mockgen/verify_stats.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/mockgen/verify_stats.py', 'run'): "MONEY",
    ('src/gsm_core/policy.py', 'PolicyBundle'): "MONEY",
    ('src/gsm_core/policy.py', 'PolicyBundle.bonus_at'): "MONEY",
    ('src/gsm_core/policy.py', 'PolicyBundle.from_record'): "MONEY",
    ('src/gsm_core/policy.py', 'PolicyBundle.has_weekly_quota'): "MONEY",
    ('src/gsm_core/policy.py', 'PolicyBundle.next_tier_gap'): "MONEY",
    ('src/gsm_core/policy.py', 'resolve_cost_params'): "MONEY",
    ('src/gsm_core/schema_registry.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/solvers/bonus_feasibility.py', 'solve'): "MONEY",
    ('src/gsm_core/solvers/capacity_alloc.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/solvers/f3_patterns.py', 'solve'): "MONEY",
    ('src/gsm_core/solvers/mission_knapsack.py', 'solve'): "MONEY",
    ('src/gsm_core/solvers/penalty_explain.py', 'solve'): "MONEY",
    ('src/gsm_core/solvers/shift_dp.py', '<toplevel>'): "MONEY",
    ('src/gsm_core/solvers/shift_dp.py', '_baseline_naive_rest'): "MONEY",
    ('src/gsm_core/solvers/shift_dp.py', '_payout_per_order'): "MONEY",
    ('src/gsm_core/solvers/shift_dp.py', '_solve_dp'): "MONEY",
    ('src/gsm_core/solvers/shift_dp.py', 'solve'): "MONEY",
    ('src/gsm_core/solvers/weekly_khoan.py', 'solve'): "MONEY",
    ('src/gsm_core/vn_format.py', 'render_number_vn'): "MONEY",
    ('src/gsm_sim/advice_bridge.py', 'AdviceActionBridge.__init__'): "MONEY",
    ('src/gsm_sim/advice_bridge.py', 'AdviceActionBridge.solver_params'): "MONEY",
    ('src/gsm_sim/behavior.py', 'AcceptDecision'): "MONEY",
    ('src/gsm_sim/behavior.py', 'accept_order'): "MONEY",
    ('src/gsm_sim/behavior.py', 'decide_accept'): "MONEY",
    ('src/gsm_sim/cli.py', 'cmd_run'): "MONEY",
    ('src/gsm_sim/dashboard.py', '<toplevel>'): "MONEY",
    ('src/gsm_sim/dashboard_defaults.py', '<toplevel>'): "MONEY",
    ('src/gsm_sim/demand.py', 'Order'): "MONEY",
    ('src/gsm_sim/demand.py', '_add_event_orders'): "MONEY",
    ('src/gsm_sim/demand.py', 'generate_orders'): "MONEY",
    # dataclass STATE — khai báo cả payout_vnd lẫn fatigue_threshold_min; khai báo không phải tính toán (đường tính ở world/_serve_trip, policy, solvers)
    ('src/gsm_sim/entities.py', 'Actor'): "NOT_MONEY",
    ('src/gsm_sim/journey.py', 'DriverJourney'): "MONEY",
    ('src/gsm_sim/journey.py', 'DriverJourney.to_dict'): "MONEY",
    ('src/gsm_sim/journey.py', 'Offer'): "MONEY",
    ('src/gsm_sim/journey.py', 'TimelineBlock'): "MONEY",
    ('src/gsm_sim/journey.py', '_income_curve'): "MONEY",
    ('src/gsm_sim/journey.py', '_offers_of'): "MONEY",
    ('src/gsm_sim/journey.py', '_timeline_of'): "MONEY",
    ('src/gsm_sim/journey.py', 'build_journey'): "MONEY",
    ('src/gsm_sim/logging_ev.py', 'write_run'): "MONEY",
    ('src/gsm_sim/metrics.py', 'summarize'): "MONEY",
    ('src/gsm_sim/multiday.py', 'DriverMemory'): "MONEY",
    ('src/gsm_sim/multiday.py', 'DriverMemory.close_week'): "MONEY",
    ('src/gsm_sim/multiday.py', 'MultiDayResult.totals'): "MONEY",
    ('src/gsm_sim/multiday.py', '_update_memory'): "MONEY",
    ('src/gsm_sim/parallel.py', '_cohort_metrics'): "MONEY",
    ('src/gsm_sim/parallel.py', '_driver_metrics'): "MONEY",
    ('src/gsm_sim/parallel.py', '_system_metrics'): "MONEY",
    ('src/gsm_sim/parallel.py', 'assert_crn'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.day_bonus'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.driver_payout_from_gross'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.from_config'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.gross_fare'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.next_tier_gap'): "MONEY",
    ('src/gsm_sim/policy.py', 'PolicyBundle.to_core_record'): "MONEY",
    ('src/gsm_sim/sim_metrics.py', 'cost_summary'): "MONEY",
    ('src/gsm_sim/sim_metrics.py', 'driver_metrics'): "MONEY",
    ('src/gsm_sim/sim_metrics.py', 'fairness_metrics'): "MONEY",
    ('src/gsm_sim/trajectory.py', 'detect_flaws'): "MONEY",
    ('src/gsm_sim/world.py', 'World.__init__'): "MONEY",
    ('src/gsm_sim/world.py', 'World._actor_proc'): "MONEY",
    ('src/gsm_sim/world.py', 'World._dispatcher_proc'): "MONEY",
    ('src/gsm_sim/world.py', 'World._do_charge'): "MONEY",
    ('src/gsm_sim/world.py', 'World._newbie_settle'): "MONEY",
    ('src/gsm_sim/world.py', 'World._serve_trip'): "MONEY",
    ('src/gsm_sim/world.py', 'World._settle_end_of_run'): "MONEY",
    ('ui/backend/app/adapters/advisor.py', '<toplevel>'): "MONEY",
    ('ui/backend/app/adapters/advisor.py', '_advice_raw'): "MONEY",
    ('ui/backend/app/adapters/advisor.py', 'build_gi'): "MONEY",
    ('ui/backend/app/adapters/mockdata.py', '_income_row'): "MONEY",
    ('ui/backend/app/adapters/mockdata.py', '_missions'): "MONEY",
    ('ui/backend/app/adapters/mockdata.py', 'driver_history'): "MONEY",
    ('ui/backend/app/adapters/mockdata.py', 'driver_state'): "MONEY",
    ('ui/backend/app/adapters/sim_pricing.py', 'quote_distance'): "MONEY",
    ('ui/backend/app/models.py', 'DriverStateResponse'): "MONEY",
    ('ui/backend/app/models.py', 'PayoutSummary'): "MONEY",
    ('ui/backend/app/models.py', 'RouteCalculateResponse'): "MONEY",
    ('ui/backend/app/models.py', 'TripStepResponse'): "MONEY",
    ('ui/backend/app/routers/sim.py', '_journey_payload'): "MONEY",
    ('ui/backend/app/routers/sim.py', 'get_ab'): "MONEY",
    ('ui/backend/app/routers/sim.py', 'get_run'): "MONEY",
    ('ui/backend/app/simulator.py', 'generate_synthetic_driver_state'): "MONEY",
    ('ui/backend/app/simulator.py', 'generate_synthetic_trip_step'): "MONEY",
}
